const NO_LIST_SUBMITTED = 'NO_LIST_SUBMITTED'
const LOW_BALANCE = 'LOW_BALANCE'
const LAST_EXECUTED_SESSION = 'LAST_EXECUTED_SESSION'

module.exports = {
  NO_LIST_SUBMITTED,
  LOW_BALANCE,
  LAST_EXECUTED_SESSION
}
